/**
 * Mosquitto-style ACL generation from the `devices` table.
 *
 * Local dev keeps `allow_anonymous true` (a laptop, one kennel) — but the ACL
 * model is real and ready: set `MOSQUITTO_ACL_PATH` and it's regenerated on
 * every claim. At Phase 9 the same rules drive EMQX's ACL.
 *
 * Mosquitto semantics: `topic read` = may SUBSCRIBE, `topic write` = may PUBLISH.
 *   device:<id>  reads  its  …/command   ·  writes its …/{status,event,ack,telemetry,location,presence,<metric>}
 *   hub:<id>     readwrite kennel/<kennelId>/#     (an on-site edge box)
 *   backend      readwrite kennel/#
 */
import { writeFile } from 'fs/promises';
import { query } from '../database/index.js';

export interface AclDevice {
  device_id: string;
  device_type: string;
  kennel_id: string | null;
  mqtt_username: string | null;
}

const DEVICE_WRITE_LEAVES = ['status', 'event', 'ack', 'telemetry', 'location', 'presence'];

export function deviceAclStanza(d: AclDevice): string {
  if (!d.mqtt_username || !d.kennel_id) return '';
  const base = `kennel/${d.kennel_id}/${d.device_type}/${d.device_id}`;
  const lines = [`user ${d.mqtt_username}`];
  if (d.device_type === 'hub') {
    lines.push(`topic readwrite kennel/${d.kennel_id}/#`);
  } else {
    lines.push(`topic read ${base}/command`);
    for (const leaf of DEVICE_WRITE_LEAVES) lines.push(`topic write ${base}/${leaf}`);
    lines.push(`topic write ${base}/+`); // metric leaves (temperature, weight, tds, …)
  }
  return lines.join('\n');
}

export function buildAcl(devices: AclDevice[], backendUser?: string): string {
  const parts: string[] = [
    '# generated by smart-pet-backend — do not edit',
    '',
  ];
  if (backendUser) {
    parts.push(`user ${backendUser}`, 'topic readwrite kennel/#', '');
  }
  for (const d of devices) {
    const s = deviceAclStanza(d);
    if (s) parts.push(s, '');
  }
  return parts.join('\n');
}

/** Regenerate the ACL file from the DB. No-op if MOSQUITTO_ACL_PATH is unset. */
export async function syncAclFile(): Promise<{ written: boolean; path?: string; devices: number }> {
  const path = process.env.MOSQUITTO_ACL_PATH;
  const devices = await query<AclDevice>(
    `SELECT device_id, device_type, kennel_id, mqtt_username
       FROM devices WHERE mqtt_username IS NOT NULL`
  );
  if (!path) return { written: false, devices: devices.length };
  const backendUser = process.env.MQTT_USERNAME || process.env.MQTT_USER || undefined;
  await writeFile(path, buildAcl(devices, backendUser), 'utf8');
  return { written: true, path, devices: devices.length };
}
